### ISSUE TITLE
Updates sometimes don't propogate

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#112]
PR: https://github.com/dlang/dmd/pull/7553

was fixed in https://github.com/dlang/ci/pull/108 and even though it was repeatedly restarted afterwards, e.g.

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7553/7/pipeline/183

It still showed;

> Checking out Revision 2427af70404bbc8878da7295d0e662a458a6a93e (v4.0.0-alpha.2)

Found by @JinShil

**Comment by wilzbach** [comment]
Rebasing the PR to `upstream/master` fixed the problem: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7553/8/pipeline/186

**Comment by ibuclaw** [comment]
It looks like its more of a timing issue, and just pot luck depending on which runner you hit.

Looking at the build history of the last 2 hours (Sunday, Jan 7, 12pm UTC)
https://ci.dlang.io/view/all/builds

Timeline is this:

Time (approx) | Change | Runner | Result
------------ | ------------ | ------------- | -------------
10:25 | D Programming Language » ci » PR-115 # 1 | runner-01.ci.lxd | Pass
10:45 | D Programming Language » ci » master # 66 | runner-02.ci.lxd | Pass
10:51 | D Programming Language » dmd » PR-7625 # 2 | runner-01.ci.lxd | Pass
10:52 | D Programming Language » dmd » PR-7624 # 2 | runner-02.ci.lxd | Fail
10:54 | D Programming Language » dmd » PR-7622 # 2 | runner-02.ci.lxd | Fail
10:54 | D Programming Language » dmd » PR-7620 # 2 | runner-02.ci.lxd | Fail
10:55 | D Programming Language » dmd » PR-7619 # 2 | runner-02.ci.lxd | Fail
11:03 | D Programming Language » dmd » PR-7617 # 13 | runner-01-gce | Pass
11:24 | D Programming Language » dmd » PR-7619 # 3 | runner-01.ci.lxd | Pass
11:25 | D Programming Language » dmd » PR-7620 # 3 | runner-02.ci.lxd | Pass

The first two are for a commit that should have fixed all builds.

The first successful build on `runner-02.ci.lxd` was around an hour later.

Looking at the logs of the failed builds, i.e: https://ci.dlang.io/job/dlang-org/job/dmd/job/PR-7619/2/consoleFull

Early on, there is a message that doesn't appear in the successful builds:
```
Replacing contents of vars/runPipeline.groovy
```
Which I can only assume is related to the "fix" in #115.

**Comment by MartinNowak** [comment]
No, Jenkins should always fetch `vars/runPipeline.groovy` from master of the ci repo.

**Comment by MartinNowak** [comment]
> was fixed in #108 and even though it was repeatedly restarted afterwards, e.g.

Because restarting, replays with the same parameters. That extends to anything checked out by Jenkins itself (dlang/ci@master, and the testee), but not the repos where we manually fetch a branch (instead of a tag) in the script.
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/activity?branch=PR-7553

**Comment by MartinNowak** [comment]
FYI @JinShil

**Comment by wilzbach** [comment]
> Because restarting, replays with the same parameters. That extends to anything checked out by Jenkins itself (dlang/ci@master, and the testee), but not the repos where we manually fetch a branch (instead of a tag) in the script.

I observed otherwise. Have a look at these logs. If replays would be with the same parameters, then "replays" shouldn't pass right?

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdruntime/activity/?branch=PR-2015
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdruntime/activity/?branch=PR-2017
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdruntime/activity/?branch=PR-2018
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdruntime/activity/?branch=PR-2020

The second last "Replay" was made _after_ the fix for dlang/ci was merged which imho clearly indicates that there's a cache.

**Comment by MartinNowak** [comment]
As I said, for the projects checked out by Jenkins itself, that's dlang/ci@master (referenced in the [Jenkinsfile](https://github.com/dlang/dmd/blob/97105b8f40b4a60c260c38d0b06684396511aea8/Jenkinsfile#L2)) and the testee (the one that triggered the build) checked-out [here](https://github.com/dlang/ci/blob/11e6aac5591a343d7523e26bf8f16c4582e6eee8/vars/runPipeline.groovy#L40).
Those two are replayed at the same state/commit, not even merging into an updated base branch (master) IIRC.

For the rest the script fetches references itself (see [here](https://github.com/dlang/ci/blob/11e6aac5591a343d7523e26bf8f16c4582e6eee8/vars/runPipeline.groovy#L51)), thus you'll get some updates even in replays.

**Comment by wilzbach** [comment]
> not even merging into an updated base branch (master) IIRC.

Hehe - Jenkins doesn't checkout the testee branch, it always checks out `master`:

https://github.com/dlang/ci/issues/120 (I found out about this the _hard_ way - see below).

> For the rest the script fetches references itself (see here), thus you'll get some updates even in replays.

The only thing that broke Jenkins yesterday was https://github.com/dlang/druntime/pull/2036 (it passed there, hence #120). I consequently added a temporary fix to the groovy script at dlang/ci (https://github.com/dlang/ci/pull/121).
Now I retriggered the druntime PRs and they still failed with the same error message (e.g. https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdruntime/detail/PR-2015/8/pipeline/209), so I'm pretty sure that there's a cache. As I said replaying after a couple of hours worked. My assumption is that `dlang/ci` only gets cloned once for a worker and doesn't get updated on a new PR job, but only due to the worker being de-provisioned and re-provisioned.

**Comment by MartinNowak** [comment]
Mmh, dlang/ci is included directly in Jenkinsfile with `library identifier: "dlang@master"`. The branch is hardcoded in the admin settings. So indeed it might be that Jenkins is updating that master ref globally.
