### ISSUE TITLE
GH API rate limit exceeded

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#133]
CI is passing:

![image](https://user-images.githubusercontent.com/4370550/35364113-ad36f550-016d-11e8-952d-2b2c4fea7cf8.png)

But it doesn't report back a success message:

![image](https://user-images.githubusercontent.com/4370550/35364131-bac7825c-016d-11e8-838c-936aa8b4aa46.png)

e.g. https://github.com/dlang/ci/pull/132 (but appeared on more PRs)

**Comment by MartinNowak** [comment]
Have you checked the raw log, st. it hides exceptions.

**Comment by MartinNowak** [comment]
Might have the same cause as #131, an outdated cached sha1 hash on GH's side.

**Comment by wilzbach** [comment]
Seen here again: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6134/1/pipeline

```
[Pipeline] End of Pipeline
Could not update commit status. Message: GitHub API rate limit exceeded
```

Do you use the same GH Token as the DLang-Bot?

See also: https://github.com/dlang-bots/dlang-bot/issues/166

**Comment by wilzbach** [comment]
Buildkite uses GitHub Apps to post the status updates, so the rate limits shouldn't affect dlang-bot.
