### ISSUE TITLE
Build important projects with -de

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#137]
When a deprecation is triggered, it should be ensured that all important repositories don't use the deprecated feature anymore. In other words, it should be the job of the person introducing the deprecation to ensure that (1) the ecosystem is ready for it and (2) suitable replacements exists.

Some projects are less active than others, so we might only want to do this for projects to which we have merge access, i.e. projects at `dlang-community`

**Comment by MartinNowak** [comment]
No, I don't agree here, sure we should have an eye on the impact of a deprecation, but it's certainly not the job of language core team to fix the whole ecosystem before deprecating sth.
Ensuring that there are alternatives et.al. should be done in the review process.
