### ISSUE TITLE
How about adding iz ? It has revealed another reg today

### ISSUE THREAD

**Issue by BBasile** [dlang/ci#177]
I've already been in contact about regressions in [IZ](https://github.com/BBasile/iz) with M.Nowak. Today again another reg revealed in this lib: https://issues.dlang.org/show_bug.cgi?id=18469

I test it on [SemaphoreCI against the nighlty](https://semaphoreci.com/bbasile/iz) since beginning of 2018 but for some reason this REG wasn't detected.

**Comment by wilzbach** [comment]
Yes. Can you send a PR against this file?

https://github.com/dlang/ci/blob/master/vars/runPipeline.groovy#L433

I think you know best how to build IZ. The Project Tester by default will parse the `scripts` section of your `.travis.yml`.
However, it won't install any dependencies, so I guess you have two options:

- use the environment variable `DETERMINISTIC_HINT` in your `travis.yml` to run a subset of your tests
- provide a custom set of build commands here

Also note that the latest stable tag will be checked out.

> but for some reason this REG wasn't detected.

The nightlies were down for the last week.

**Comment by BBasile** [comment]
Yes custom command is the better option. On Travis i also do some stuff with valgrind so a bit too much for here i suppose.
