### ISSUE TITLE
integrate style checks from CircleCI tests

### ISSUE THREAD

**Issue by MartinNowak** [dlang/ci#18]
Simply reducing the number CIs, see https://github.com/dlang/phobos/blob/395ae88ac75ee0c03f6475ad4a5b073cfaf4e084/circleci.sh#L133-L135.

**Comment by wilzbach** [comment]
If DMD would have a `style` target we could do something like:

```
stage ("Style checks") {
    def repo_name = /python3 -c "import sys, json; print(json.load(sys.stdin)['repository']['name'])"/
    sh 'make -C ${repo_name} -f posix.mak style'
}
```

**Comment by wilzbach** [comment]
> If DMD would have a style target we could do something like:

https://github.com/dlang/dmd/pull/6555
