### ISSUE TITLE
Non-optional dependency diet-ng of vibe-d:http not found in dependency tree!?.

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#190]
This happens very often now on the Jenkins CI.

Related issues
- https://github.com/dlang/dub/issues/1375
- https://github.com/dlang/dub/issues/1180
- https://github.com/dlang/dub/pull/1148
- https://github.com/dlang/dub/issues/1112
- https://github.com/dlang/dub/issues/986
- https://github.com/dlang/dub/issues/865

Maybe it's a regression of https://github.com/dlang/dub/issues/828 / https://github.com/dlang/dub/issues/803? 

Example: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-5822/6/pipeline

**Comment by wilzbach** [comment]
So this definitely looks a dub regression, both openssl nor botan had changes in the last weeks:

https://github.com/etcimon/botan/blob/master/dub.json#L118
http://code.dlang.org/packages/openssl

**Comment by wilzbach** [comment]
More examples:
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6400/7/pipeline
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6396/3/pipeline

> Fetching openssl 1.1.6+1.0.1g (getting selected version)...
> ...
> Non-optional dependency openssl of botan not found in dependency tree!?.

Also in diet-ng (with openssl too)

- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6391/7/pipeline
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-5822/6/pipeline/
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-5822/6/pipeline

Also in vibe-d+libevent:
- https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6388/13/pipeline

```
+ cd examples/app_skeleton
+ dub build --compiler=dmd --override-config=vibe-d:core/libevent --build-mode=separate
Fetching diet-ng 1.4.5 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
```

**Comment by wilzbach** [comment]
Or in dlang-requests:

```
+ dub build -c std
Fetching diet-ng 1.4.5 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
Non-optional dependency diet-ng of vibe-d:http not found in dependency tree!?.
script returned exit code 2
```

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6386/12/pipeline

**Comment by JackStouffer** [comment]
Is there a new dub issue for this? It seems to be happening on all PRs?

**Comment by wilzbach** [comment]
> Is there a new dub issue for this? 

No, but there's https://github.com/dlang/dub/pull/1148 which might fix this.

> It seems to be happening on all PRs?

Yes and I haven't been able to reproduce it locally so far.
I know found https://github.com/dlang/dub/issues/1112 which reproduces the same error message (not sure whether it's the same cause yet).

**Comment by wilzbach** [comment]
Update: I tried merging https://github.com/dlang/dub/pull/1148 into dub at dlang/ci in https://github.com/dlang/ci/pull/191 and the tests are still failing (https://github.com/dlang/dub/pull/1148 fixes the test case from dlang/dub#1112 though)

**Comment by wilzbach** [comment]
I have a new assumption. Some project now started to depend on a version that isn't part of the registry mirror. This CI uses (https://code-mirror.dlang.io) and it seems like the update job broke:

![image](https://user-images.githubusercontent.com/4370550/38232420-35d04162-3717-11e8-897a-69d5b2c6d5e1.png)

**Comment by wilzbach** [comment]
Hmm the patching of the default registry was removed in https://github.com/dlang/ci/pull/106, so it should query code.dlang.org by default.

Maybe @s-ludwig has an idea?

**Comment by s-ludwig** [comment]
> I have a new assumption. Some project now started to depend on a version that isn't part of the registry mirror. 

I think this is the case, at least whenever code.dlang.org is not reachable. Unfortunately it's still sometimes starting to swap and then needs a while to stabilize again. We should really look into putting code.dlang.org on its own machine.

**Comment by MartinNowak** [comment]
Just updated code-mirror.dlang.io, the update was hanging due to a schema change.
https://github.com/dlang/ci/pull/197
