### ISSUE TITLE
Use a custom context name

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#24]
This is an enhancement request.

Apparently the default context is set to `continuous-integration/jenkins/pr-merge` which looks quite long and could something more expressive like `dlang/projects`

According to [the docs](https://github.com/jenkinsci/ghprb-plugin/blob/master/README.md) their DSL can be used for this:

```
  wrappers {
        downstreamCommitStatus {
            context('CONTEXT NAME')
        }
  }
```

**Comment by MartinNowak** [comment]
We're not using the declarative syntax, but the direct groovy commands. Also we're using https://plugins.jenkins.io/github-organization-folder (now replaced by https://plugins.jenkins.io/github-branch-source), not the old GH PR builder. Changing that names looks like it'd need manual status updates, https://jenkins.io/doc/pipeline/steps/gitlab-plugin/, doable.

**Comment by MartinNowak** [comment]
Or this https://jenkins.io/doc/pipeline/steps/github-pullrequest.

**Comment by MartinNowak** [comment]
Context names are long, but clear and fine.
