### ISSUE TITLE
Find a way to simulate the dmd, druntime and phobos repository builds directly at dlang/ci

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#295]
A few builds: style, coverage, now dlang/phobos and the clone + checkout code is a bit different for these three core repositories and this code doesn't get tested on a PR to dlang/ci.

I guess we have two possibilities:
- modify `buildkite.sh` to be callable in "simulate" mode (and call it multiple times and concat the YAML)
- add ci-dmd, ci-druntime, ... pipelines which do the same things as the normal dmd pipeline would do

For both possibilities, we should
- [ ] figure out a way to fake the PR number (or at least avoiding checking out the wrong one)
- [ ] avoid building all projects multiple times (only a few targets are different for dmd & co)

**Comment by MartinNowak** [comment]
You want to simulate the buildkite checkout on PRs to dlang/ci?
I'd say drop that stuff, it's not even testing merged PRs (just the branch head), here is an approach to override the checkout phase https://github.com/dlang/ci/issues/335#issue-377625848.
