### ISSUE TITLE
building LaurentTreguier/dls regularly crashes dmd (2.082.0)

### ISSUE THREAD

**Issue by MartinNowak** [dlang/ci#305]
See e.g. https://buildkite.com/dlang/druntime/builds/211#cbaf4e67-968a-41a1-9cc3-8afb85e18991.

**Comment by wilzbach** [comment]
It seems like it runs on the cheaper VPS machines and Buildkites auto-restart doesn't try to run it on other machines.

**Comment by wilzbach** [comment]
See https://github.com/dlang/ci/pull/319
