### ISSUE TITLE
CI's are not consistent in their output directories

### ISSUE THREAD

**Issue by thewilsonator** [dlang/ci#309]
The autotester outputs to e.g. `generated/fail_compilation/fail_compilation/`, while semaphore outputs to `test_results/fail_compilation/`. This makes it impossible to write valid `TEST_OUTPUT:` tests for cases where error outputs include the object output directory. I think they should all match the autotester.

This is blocking https://github.com/dlang/dmd/pull/8677

**Comment by wilzbach** [comment]
No you should use the variables which refer to the output directory like `RESULTS_DIR` or output base.

See also: https://github.com/dlang/dmd/blob/master/test/README.md
