### ISSUE TITLE
Buildkite seems to run the Style test with an  older compiler

### ISSUE THREAD

**Issue by BBasile** [dlang/ci#312]
Possibly the host DC instead of the generated one.

**Comment by Geod24** [comment]
Can you give more details ? What did you observe ?

**Comment by BBasile** [comment]
Look at this : https://buildkite.com/dlang/phobos/builds/405#7fdba279-6416-402b-9006-476df743b7ac/82-104. It shows that it's not DMD 2.082 that's used, since the new trait is not recognized

**Comment by BBasile** [comment]
I was able to verify that only the Style suite is affected (https://buildkite.com/dlang/phobos/builds/406#12871fa6-e06e-40a6-970e-3b0e098e15bb/108-114)

**Comment by BBasile** [comment]
I know the transition from Jenkins is not complete and that for now the failures are not blockers but i just wanted to keep track of this oddity.

**Comment by ZombineDev** [comment]
Actually the transition to Buildkite should be complete and all issues must be addressed, so it's good that you point this issue out.

**Comment by BBasile** [comment]
I've relaunched by hand and [it's green now](https://buildkite.com/dlang/phobos/builds/419#3ef47950-8e8f-44d8-8cb7-e5b4df381abf). I have no idea why (no change in CI, no rebase in my PR). Closing for now.
