### ISSUE TITLE
New release of LaurentTreguier/dls broke the build

### ISSUE THREAD

**Issue by Geod24** [dlang/ci#315]
New release about 19 hours ago: https://github.com/d-language-server/dls/releases/tag/v0.15.0
All build fail with:

```
Non-optional dependency dcd of dls not found in dependency tree!?.
Non-optional dependency dcd of dls not found in dependency tree!?.
```

CC @LaurentTreguier

**Comment by Geod24** [comment]
Also, looks like the repo was moved to https://github.com/d-language-server/dls so we should probably upgrade the URL.

**Comment by LaurentTreguier** [comment]
What I've done in `v0.15.0` is fetching the dependencies manually and building with `dub build --nodeps` to bypass dependency conflicts.
I see the CI runs the Travis test script. Is there a reason why doesn't the CI also run the `before_script` part ? (this is where I'm fetching the dependencies)

**Comment by jacob-carlborg** [comment]
> Is there a specific reason why doesn't the CI also run the before_script part ? (this is where I'm fetching the dependencies)

I'm guessing for simplicity. Custom build commands can be added here:

https://github.com/dlang/ci/blob/eb81cf4f6e5e882fcce91c5a55a45f214a140935/buildkite/build_project.sh#L85

**Comment by Geod24** [comment]
Yeah, it's solely about simplicity / no one bothered to implement it yet.
As @jacob-carlborg mentioned, you could also edit the Buildkite-side to fetch the dependencies

**Comment by LaurentTreguier** [comment]
I see. I've moved the manual dependency fetch in my `.travis.yml`, since I may just remove that part when I don't need it anymore; so no need to put it as a custom command here.

**Comment by wilzbach** [comment]
> What I've done in `v0.15.0` is fetching the dependencies manually and building with `dub build --nodeps` to bypass dependency conflicts.
> I see the CI runs the Travis test script. Is there a specific reason why doesn't the CI also run the `before_script` part ? (this is where I'm fetching the dependencies)
> Of course I can always just merge my `before_script` in the `script` part if it's simpler.

Because typically constant dependencies or settings are directly installed on the buildkite year runners. For example, ld.gold is already the default linker.

**Comment by wilzbach** [comment]
> I see. I've moved the manual dependency fetch in my `.travis.yml`, since I may just remove that part when I don't need it anymore; so no need to put it as a custom command here.

If you edit your Travis config, a new release tag will be required as buildkite will test the latest stable release.

**Comment by Geod24** [comment]
Yep it's fixed

**Comment by Geod24** [comment]
Merci @LaurentTreguier !

**Comment by LaurentTreguier** [comment]
@Geod24 you're welcome !
