### ISSUE TITLE
style test relies on adjacent dmd repo being present

### ISSUE THREAD

**Issue by MartinNowak** [dlang/ci#335]
Fails with fresh on-demand agents when `make -f posix.mak style` tries to include `../dmd/osmodel.mak`.
https://buildkite.com/dlang/phobos/builds/552#100bbbc3-6b0d-44af-861d-99a0791563dc
Just didn't happen on the long-running buildkite agents because they still had a previous dlang/dmd repo leftover.
The whole folder setup is quite messy atm. and we should consider to rewrite it, using a custom noop checkout hook and doing the checkouts manually into an empty working directory.
Checkout hooks can be installed on the agents under `/etc/buildkite-agent/hooks/checkout`.
This would also avoid checkouts for every project being tested.

**Comment by MartinNowak** [comment]
@wilzbach

**Comment by wilzbach** [comment]
This was fixed with https://github.com/dlang/ci/pull/340. However, now it fails because DMD is segfaulting while building Dscanner.
This has been fixed at Dscanner and there's a PR to update Dscanner at Phobos: https://github.com/dlang/phobos/pull/6783

**Comment by BBasile** [comment]
Yes this is coming. Maybe just a few filtering rules to adjust.

**Comment by wilzbach** [comment]
> The whole folder setup is quite messy atm. and we should consider to rewrite it, using a custom noop checkout hook and doing the checkouts manually into an empty working directory.

Moved this to https://github.com/dlang/ci/issues/358

**Comment by wilzbach** [comment]
Closing as I moved the main issue to #358 and the style test have been fixed.
