### ISSUE TITLE
The automatically spawned buildkite agents should have a lower queue priority than the constant ones

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#348]
The "always on" agents seem to be a lot faster, so they should have a higher queue priority.

See also: https://github.com/dlang/ci/pull/321

**Comment by wilzbach** [comment]
Ah apparently this is already done:

https://github.com/dlang/ci/blob/c6b5a9b70ef41c1b68e26cd293bf5264cd169a28/ansible/gen_ci-agent_hcloud_image.yml#L89

Not sure why Buildkite then often assigns work to the on-demand agents (even if the static ones are idling)...

**Comment by wilzbach** [comment]
Hmm it looks like https://github.com/dlang/ci/pull/321 hasn't been deployed yet then.

```
> ssh buildkite-agent-04.ci.dlang.io
>> grep priority /etc/buildkite-agent/buildkite-agent.cfg 
# The priority of the agent (higher priorities are assigned work first)
priority=1
```

**Comment by MartinNowak** [comment]
The now reached goal was to fully replace the permanent sever, hence the preference for on-demand agents.
