### ISSUE TITLE
Buildkite: dub pipeline fails due to dls

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#360]
see https://buildkite.com/dlang/dub/builds/308

Probably related: https://github.com/d-language-server/dls/pull/17 and https://github.com/dlang/dub/pull/1601

CC @ZombineDev

**Comment by wilzbach** [comment]
I guess the problem is that we're checking out v0.19.0 and not 0.19.1

![image](https://user-images.githubusercontent.com/4370550/49366219-11212d80-f6e9-11e8-8a15-481819c1b0eb.png)

**Comment by wilzbach** [comment]
but it's downloading the new dub with the DMD patch:

```
Fetching dub 1.12.1-alpha.1 (getting selected version)...
```

```
==========================================================================================================================
--
  | Test directory /var/lib/buildkite-agent/builds/buildkite-agent-04-1/dlang/dub/build/d-language-server-dls/tests/formatting
  | ==========================================================================================================================
  | * Message initialize                   : PASS ✔
  | * Message initialized                  : PASS ✔
  | * Message textDocument_formatting      : FAIL ✘
```

**Comment by wilzbach** [comment]
CC @LaurentTreguier - maybe you did any recent changes that could be related?
Also interestingly enough it only fails for the `dub` pipeline and not for any of the other core repositories (which also use `dub` master to build the newest `dub`) which suggests sth. else going on here :/

**Comment by LaurentTreguier** [comment]
Switching to v0.19.1 shouldn't change anything I think.
I am baffled by this. The tests for v0.19.0 [pass on Travis](https://travis-ci.org/d-language-server/dls/jobs/461928195) without any problem. From the diff being displayed, it looks like for some reason spaces are being replaced with tabs. I have no clue how this can be happening.

**Comment by LaurentTreguier** [comment]
I tried (and failed) to reproduce the problem in a fresh new Ubuntu 16.04 container.
I can only get the same result by manually changing JSON files used in the tests, either changing or removing some of their properties. To be more precise, in the file [tests/formatting/messages/textDocument_formatting.in.json](https://github.com/d-language-server/dls/blob/master/tests/formatting/messages/textDocument_formatting.in.json), if the `options` property is removed, you'll get a result similar to the fail on Buildkite.
However, since the repo is simply getting cloned, I don't see how they could be changed.
I see that among the agent's info, its IP address is displayed. Is there any way to connect to the agent to try to investigate ?

**Comment by wilzbach** [comment]
> However, since the repo is simply getting cloned, I don't see how they could be changed.

I have no idea either, but I experimented a bit with it here:

https://github.com/dlang/ci/pull/369

Though it will pass anyway, because the failure is only observable for the dlang/dub pipeline.
In fact I think the repo is cloned inside the DUB repo, because Buildkite by default clones the origin repo. I was looking at the files that make dub special and found a `.editorconfig` file. Maybe that's the root cause?

Otherwise is there any way for us to patch the test out?
`DETERMINISTIC_HINT` will be set to `1` by our test runner on Buildkite, so maybe that would help to make the test not fail here?

> I see that among the agent's info, its IP address is displayed. Is there any way to connect to the agent to try to investigate ?

Not that easily as the agents get automatically commissioned and decommissioned and it only happens for the dlang/dub repo.

**Comment by LaurentTreguier** [comment]
> I have no idea either, but I experimented a bit with it here:
> 
> #369
> 
> Though it will pass anyway, because the failure is only observable for the dlang/dub pipeline.
> In fact I think the repo is cloned inside the DUB repo, because Buildkite by default clones the origin repo. I was looking at the files that make dub special and found a `.editorconfig` file. Maybe that's the root cause?

Yes, that could very well be it ! Looking at [DFMT's code](https://github.com/dlang-community/dfmt/blob/v0.8.3/src/dfmt/editorconfig.d#L138), when trying to load the config for a specific path, it will apparently look for `.editorconfig` files in all parent directories as well... So DUB's `.editorconfig` is probably getting picked up automatically even if it's not in the test's workspace.

**Comment by wilzbach** [comment]
Cool! I will give https://github.com/dlang/ci/pull/369 a try then.

**Comment by wilzbach** [comment]
Yup, looks like this fixed the issue - see e.g. https://buildkite.com/dlang/dub/builds/349
