### ISSUE TITLE
Use EC2 Spot instances

### ISSUE THREAD

**Issue by MartinNowak** [dlang/ci#37]
Given the big amount of idle time, and the not so urgent workload, using EC2 spot instances might heavily reduce server cost, while at the same time providing more capacity when needed.
[jenkinsci/ec2-fleet-plugin: The EC2 Spot Jenkins plugin launches EC2 Spot instances as worker nodes for Jenkins CI server, automatically scaling the capacity with the load.](https://github.com/jenkinsci/ec2-fleet-plugin)
For example [c4.xlarge](https://aws.amazon.com/ec2/instance-types/#c4) instances in US EAST (Ohio) cost about 0.03$/hr. most of the time.

**Comment by wilzbach** [comment]
AFAICT you use GCE instances now - so I think this can be closed?

**Comment by MartinNowak** [comment]
And soon https://www.hetzner.de/cloud instances ;).
