### ISSUE TITLE
Why the hell does the style check still use dparse 0.8.8 ?

### ISSUE THREAD

**Issue by BBasile** [dlang/ci#375]
See [log](https://buildkite.com/dlang/phobos/builds/942#2ef9af44-a60a-4720-adf7-50c0527690bd/277-824). Then necessarily there are [parse errors](https://buildkite.com/dlang/phobos/builds/942#2ef9af44-a60a-4720-adf7-50c0527690bd/277-869) that wouldn't happen with dparse 0.10.12.

Nobody noticed before yesterday because this doesn't make the check failing. 
The D-Scanner git hash of in dmd and phobos makefiles are up to date now and this still happens.

**Comment by wilzbach** [comment]
Cause of the `tests_extractor` here: https://github.com/dlang/tools/blob/master/tests_extractor.d

**Comment by wilzbach** [comment]
PR https://github.com/dlang/tools/pull/363

**Comment by BBasile** [comment]
thanks

**Comment by wilzbach** [comment]
There's also a bump at dlang.org required: https://github.com/dlang/dlang.org/pull/2551
