### ISSUE TITLE
`travis_get_script` should use `set -e`

### ISSUE THREAD

**Issue by Geod24** [dlang/ci#430]
Actually I would suggest `set -xeu`.
Currently, for multi-line script, only the last line is taken into account.
This can be seen for example with `diet-ng`, which will always succeed because the last line is an mkdir + cd: https://github.com/rejectedsoftware/diet-ng/blob/e2e947f24faaa71a4bab9dd8bda6f93375c67755/.travis.yml#L41-L50

**Comment by wilzbach** [comment]
Fix https://github.com/dlang/ci/pull/431
