### ISSUE TITLE
Extend Cookie expiration period

### ISSUE THREAD

**Issue by wilzbach** [dlang/ci#92]
The cookies are currently only saved for the current session:

![image](https://user-images.githubusercontent.com/4370550/33587210-4c44ae90-d96d-11e7-8df2-d8b582eb42d2.png)

Any chance we could set the expiration to sth. more convenient like 30 days?

**Comment by MartinNowak** [comment]
I moved the login button to the GH landing page already, feel free to look for sth., but I don't think it's worth to spent time on this.
https://github.com/jenkinsci/blueocean-plugin/pull/1260
